export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Checkout } from "./Checkout";
export { default as Category } from "./Category";
export { default as SignIn } from "./SignIn";
export { default as SignUp } from "./SignUp";
export { default as ProductDetail } from "./ProductDetail"
export { default as Success } from "./Success"
export { default as Cancel } from "./Cancel"
export { default as MyOrders } from "./MyOrders"
